### ISSUE TITLE
Default widget builder returns Container() 

### ISSUE THREAD

**Issue by CosmicPangolin** [leocavalcante/Flutter-ReduRx#5]
Hi,

The default widget builder for ReduRx returns a Container() for null data - this causes two problems:

1) Sometimes Flutter expects a RenderSliver instead of a RenderBox, so this implementation throws a framework error when the appropriate 'empty' widget should be SliverFillRemaining();

2) Returning Container() assumes that the developer doesn't want to use null as a check for other build logic.

Would it be possible to make the following change?

` @override
Widget build(BuildContext context) {
    return StreamBuilder<P>(
      stream: _stream,
      builder: (context, snapshot) {
        if (snapshot.data == null && !nullable) {
          return Container();
        }
        _prev = snapshot.data;
        return builder(_prev);
      },
    );
   }
`

====>

` @override
  Widget build(BuildContext context) {
    return StreamBuilder<P>(
      stream: _stream,
      builder: (context, snapshot) {
        _prev = snapshot.data;
        return builder(_prev);
      },
    );
  }
`

**Comment by leocavalcante** [comment]
Hi @CosmicPangolin 
Sorry it isn't documented, but you can add a `nullable` property on `Connect`:

```dart
Connect<State, String>(
  convert: (state) => state.title,
  where: (oldTitle, newTitle) => newTitle != oldTitle,
  builder: (title) => Text(title),
  nullable: true,
)
```

Then it will call your `builder` function with a possible `null` value.

**Comment by CosmicPangolin** [comment]
Oh I see, thank you! I have one more question..

I notice when performing a hot restart, the first Connect builder returns null first, and the correct value second, even if the Provider.of<state> object exists -- 

`
Widget build(BuildContext context) {

    return MaterialApp(

      home: Connect<AppState, bool> (

        nullable: true,

        convert: (state) => state.loginCheckCompleted,

        where: (prev, next) => prev != next,

        builder: (bool) {

          print(Provider.of<AppState>(context).store.state.loginCheckCompleted); //prints TRUE  2x

          print(bool); //prints NULL then rebuild => prints TRUE

Why is that?

Thank you!!

**Comment by leocavalcante** [comment]
That is the behavior of `StreamBuilder`. `Stream` and `builder` timings are actually decoupled, that is why you get the value asking directly to the Stream but not in the `builder`'s Snapshot:

> Widget rebuilding is scheduled by each interaction, using State.setState, but is otherwise decoupled from the timing of the stream. The builder is called at the discretion of the Flutter pipeline, and will thus receive a timing-dependent sub-sequence of the snapshots that represent the interaction with the stream. [1]

You could probably tackle this with `initialData`:
> The initial snapshot data can be controlled by specifying initialData. This should be used to ensure that the first frame has the expected value, as the builder will always be called before the stream listener has a chance to be processed. [1]

I'll leave your issue open to work on something for that.

[1] https://docs.flutter.io/flutter/widgets/StreamBuilder-class.html
